// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlddldsfddkvjkvrqway.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsZGRsZHNmZGRrdmprdnJxd2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzUwNDEsImV4cCI6MjA2NTMxMTA0MX0._D-ZKybo_M2PUmzUvyfBRqGIvGsMhihgAV82QfG1504";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);